### ISSUE TITLE
There is a problem running Pyinstaller GUI in Ubuntu 16.04

### ISSUE THREAD

**Issue by aghaPathan** [vsantiago113/PyInstallerGUI#1]
Traceback (most recent call last):
  File "PyInstallerGUI.py", line 336, in <module>
    main()
  File "PyInstallerGUI.py", line 330, in main
    root.wm_iconbitmap('images/python.ico')
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1697, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "images/python.ico" not defined

**Comment by aghaPathan** [comment]
Fixed it with this https://github.com/python-pillow/Pillow/issues/322

**Comment by vsantiago113** [comment]
Thanks for letting me know about this issue and sharing a solution.

**Comment by murtuzamdahod** [comment]
> Fixed it with this [python-pillow/Pillow#322](https://github.com/python-pillow/Pillow/issues/322)

How did you solved this with PIL?

**Comment by vsantiago113** [comment]
I think it was by installing Pillow.
