### ISSUE TITLE
Missing functionalities 

### ISSUE THREAD

**Issue by aghaPathan** [vsantiago113/PyInstallerGUI#2]
How to hook multiple modules and directories in this GUI?

**Comment by vsantiago113** [comment]
If you need to hook modules, if they are regular python modules they get added automatically by PyInstaller as far as they are import somewhere in your application. If you have other directories like images or other executables you need to copy the directories back where they belong after you build the executable.

**Comment by vsantiago113** [comment]
Let me know if you have more questions.
